version: '3.8'

services:
  fastapi-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    environment: 
      - PYTHONUNBUFFERED=1
    env_file:
      - .env